# Generated by Django 3.0.7 on 2021-11-04 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Diner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('house_location_lat', models.FloatField(verbose_name='Home Location Latitude')),
                ('house_location_long', models.FloatField(verbose_name='Home Location Longitude')),
                ('diet_types', models.ManyToManyField(blank=True, to='restaurants.DietType')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('location_lat', models.FloatField(verbose_name='Location Latitude')),
                ('location_long', models.FloatField(verbose_name='Location Longitude')),
                ('diet_endorsement_types', models.ManyToManyField(blank=True, to='restaurants.DietType')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('diners', models.ManyToManyField(to='restaurants.Diner')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Table')),
            ],
        ),
        migrations.AddConstraint(
            model_name='diettype',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
